### ISSUE TITLE
No context menu on a forum reply box

### ISSUE THREAD

**Issue by ZarkBit** [sblask/firefox-simple-form-fill#1]
not sure how to present this to you
Screenshot: http://bit.ly/1L6NG5Y

Here's the respective line from the Element Inspector.
textarea class="markItUpEditor" id="markItUp" cols="75" rows="18" name="body"></textarea

**Comment by sblask** [comment]
I uploaded a new version(1.0.2) that should fix this. Just needs to go through review(which usually takes less than a day).
