### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by fedorvinogradov** [sblask/firefox-simple-form-fill#3]
Good day. First of all you have a great addon - it's simple and small.

I have two proposals for the future development:
1. I have several strings which look like "65795204-6303-4c6a-988a-f23bcd4b5b11" and which I cannot remember by heart. So it would be convenient to have a possibility to give a label for a string. This label shouldn't be mandatory.
2. It also connects to the first request. This string "65795204-6303-4c6a-988a-f23bcd4b5b11" is inserted in the first input field and then distributed automatically through the other fields. So when it is typed it cannot be selected altogether thus cannot be added to simple form fill. So it would be nice to have a "plus" or "add" button in the addon's submenu to add strings manually so you don't have to go to the firefox extensions' list and open options of your adddon.

**Comment by sblask** [comment]
1: I have the same issue for a few numbers and I simply append a label to the number that I remove after filling. Maybe not the most convenient way, but the I wouldn't know how to handle the label in a good way.
2: you can already do that, but the `add` entry only appears when you make a selection.

**Comment by fedorvinogradov** [comment]
Thanks for ideas

**Comment by dooker123** [comment]
there used to some great find and replace shareware that had column masks.  so as to say, you could select where from left to right, the action of insertion or replacement text would flow.  In the case of serial numbers only the difference out from the left need be pasted.

another solution, if i read you rproblem right,  is to enter the number to the point where differences occur.  then you add the "suffix" varied text, each string on a line.  I use this method to build emails for an alias sefvice i use.  i type the recip., then cut it, and type "@" which triggers SFFill and i paste the non changing address fragments, and cursor to the front and paste the recip.  a bit clumsy, but for a few times a day max...  It would be nice to have some more edit controls, but until i can write code i can't tell how difficult it should be.    :)

**Comment by sblask** [comment]
This is an old issue, you can use the comment feature to add labels.
