### ISSUE TITLE
Location of file

### ISSUE THREAD

**Issue by KentLSmith** [sblask/firefox-simple-form-fill#4]
Where will the file used to feed the Simple Form fill be located.  I'd like to edit it.

**Comment by sblask** [comment]
There is no file, only the field in the preferences.

**Comment by JohnComstock** [comment]
This add-on is a favorite in our department, and we use it all the time with a couple of our internal systems. Unfortunately, after getting the 1.5.0 update, the add-on stopped working. We no longer get the right-click context menu at all, and the Edit button is not appearing on the Simple Form Fill 1.5.0 preference window. Version 1.04 still works fine. We're running FireFox ESR 45.8.0 on Windows 7.
Some screen shots:
![nocontextmenu](https://cloud.githubusercontent.com/assets/26929594/24713723/18840fce-19ec-11e7-8d4a-1f6db4632b95.png)
![nopreferences](https://cloud.githubusercontent.com/assets/26929594/24713825/5a1b2e2c-19ec-11e7-9a0b-c47f3afc18b1.png)

For now, we've downgraded back to 1.04, but we'd like to stay up to date.

**Comment by sblask** [comment]
@JohnComstock Happy to hear you like Simple Form Fill, however, up to date means in this case migration to webextension, which will not work for your version of Firefox. All I can do is restrict the Firefox versions for the new add-on version so you won't be upgraded again...

**Comment by JohnComstock** [comment]
@sblask, I was afraid it might be something like that. We'll stick with version 1.0.4 until we update our browser. Thanks for the quick response!
