### ISSUE TITLE
comments?

### ISSUE THREAD

**Issue by KentLSmith** [sblask/firefox-simple-form-fill#5]
Can we add comments to an entry?  I have several login strings that are all numbers.  I don't know which is which when I access simple form fill

**Comment by sblask** [comment]
You can do whatever you want, but I won't add a special feature for that. I have the same situation and I simply append something to the numbers I have and the delete it after filling into an input...

**Comment by sblask** [comment]
Nevermind what I wrote earlier, while I was doing some other improvements/fixes, adding a change for this wasn't too hard. You can try the latest build in the `Development Channel` section on https://addons.mozilla.org/en-US/firefox/addon/simple-form-fill/. You'll need to configure the comment string in the preferences first and then you're good to go. Re-open this issue if you have any trouble.
