### ISSUE TITLE
Incompatibility with login autofill in v2

### ISSUE THREAD

**Issue by bintoro** [sblask/firefox-simple-form-fill#6]
I installed v2.0.1b to try out the autocomplete feature (didn't understand how to use it in v1.5.0), and it seems to interfere with the built-in login autofill. When there are multiple logins stored for a website, selecting an account using the arrow keys no longer works.

I'm using Nightly 55.0a1.

**Comment by sblask** [comment]
I don't use Firefox' autofill feature, but there is also interference with autocompletes on websites. Unfortunately I think there is nothing much I can do about it. The autocomplete works mostly fine for me, but if it doesn't work for you the only thing you can do is to disable it...
