### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by maverick74** [sblask/firefox-simple-form-fill#7]
Here's what i would suggest:

1. Auto Fill Forms on page load option (no clicks)
2. Allow to save/delete/update the data of the saved forms really easy
3. Ability to save and restore the forms auto-complete data

**Comment by sblask** [comment]
These suggestions would make this add-on to something completely different from what it's supposed to be: simple. There are also plenty of add-ons out there that already do what you're asking for.

**Comment by maverick74** [comment]
Hi.

Thanks for your reply.

Other addons such as??? The ones i know - AutoFormer - are not e10s or webextensions compatible. 
Do you know any that is?

Thanks

**Comment by sblask** [comment]
Before I wrote this add-on I checked a few others, there were at least 3 as far as I remember. e10s or webextension is a different story though. You'll have to do some research. LastPass might be a good bet. They offer form filling and as it's a company behind it, they'll for sure make it compatible...
